### ISSUE TITLE
Book Review

### ISSUE THREAD

**Issue by WHBSmith** [alexandrahotti/Solutions-to-Problems-in-Bayesian-Statistics#1]
Hi Alexandra,

I am a PhD student going through some of Lambert's early video lectures on Bayes and they're really good. I recently realised that he later brought out a book and a different youtube channel with new lectures especially for the book. I was just wondering how long it took you to work through the book and what level would you recommend it to?

Will

**Comment by alexandrahotti** [comment]
Hi Will,
It took me about 2-3 months to read through the book, watch the videos, and complete the exercises. However, I skipped some exercises in each chapter, and I completely skipped the last three chapters of the book.

Lambert focuses on providing the reader with an intuitive understanding of Bayesian statistics and MCMC methods. The exercises do assume some prior mathematical knowledge.

All in all, I would mainly recommend this book to someone who wants to gain an intuitive understanding of Bayesian statistics!

Best,
Alex
