### ISSUE TITLE
R code 

### ISSUE THREAD

**Issue by ghost** [alexandrahotti/Solutions-to-Problems-in-Bayesian-Statistics#2]
Hello, 
Is there a text file for R code and Stan files presented in chapters 16-19 in the book. it would be very helpful to run them directly instead of typing them one by one.
Best regard.

**Comment by alexandrahotti** [comment]
Hi!
Not that I am aware of, unfortunately.

You could write to the author Ben Lambert and ask him about it.
Here is his email: ben.c.lambert@gmail.com
Here is his github: https://github.com/ben18785

Good luck!
Best,
/Alex

**Comment by ghost** [comment]
Thank you. I will write to him.
Regards

**Comment by ghost** [comment]
I contacted the author and he kindly provide me with the link the website where all required material can be found.
the like is
https://ben-lambert.com/a-students-guide-to-bayesian-statistics/

Thank you again.
